# Site settings
title:            blog.rymo.io
email:            author@blog.rymo.io
description:      > # This is the personal blog of Ryan Morrissey. My passions are family,
                  technology and the outdoors. You can find me rock climbing, fly fishing,
                  stand up paddleboarding, building web apps, contributing to open source
                  projects, snapping pictures, or cooking in the kitchen.
baseurl:          "" # the subpath of your site, e.g. /blog/
url:              "http://blog.rymo.io" # the base hostname & protocol for your site
twitter_username: rymoio
github_username:  rymoio

# Handling Reading
safe:         false
future:       false
show_drafts:  false
include:      [".htaccess"]
exclude:      ["README.md", "LICENSE", "bower.json", ".bowerrc", ".gitignore", "package.json", "src", ".sass_cache", "node_modules"]
keep_files:   [".git"]
encoding:     "utf-8"
markdown_ext: "md,markdown,mkdown,mkdn,mkd"
timezone:     America/New_York

# Conversion
markdown:          kramdown
highlighter:       pygments
lsi:               false

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: true

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

# Plugins
whitelist: []
gems:      []

# Outputting
permalink:           /:year/:month/:title
relative_permalinks: true
paginate_path:       /page:num
paginate:            5


# Category and Tag pages
categories:
  url: /categories/
  title_prefix: "category: "
  layout: category.html
tags:
  url: /tags/
  title_prefix: "tag: "
  layout: tag.html

# Jekyll archives
monthly_archive:
  layout: month
  path: /archives/


# Humanize
humanize:
  date_format: "%m %b %Y"